// generated by @ng-toolkit/universal
const port = process.env.PORT || 8080;
const server = require('./dist/server');
const mailController = require('./server/controller/sendMail');

server.app.post('/sendEmail', mailController.sendNotify);

server.app.listen(port, () => {
  console.log("Listening on: http://localhost:" + port);
});
